notifications:
  email: false

language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2

before_install:
  - gem install bundler

env:
 - "RAILS_VERSION=4.2.3"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true