notifications:
  email: false

language: ruby
sudo: false
rvm:
  - 2.5.5

before_install:
  - gem install bundler

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
